version: '3.8'
services:
  web:
    build:
      context: .
    environment:
      RAILS_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
