version: '3.8'
services:
  web:
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
      - ./tmp/cache:/app/tmp/cache
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p 3000"
  db:
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
