name: Rails Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 60
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.5
        bundler-cache: true

    - name: Disable bundler frozen mode
      run: bundle config set frozen false

    - name: Install dependencies
      run: bundle install

    - name: Check DB readiness
      run: |
        for i in {1..20}; do
          if pg_isready -h localhost -U postgres; then  # ここを「localhost」に修正
            echo "Database is ready!"
            break
          fi
          echo "Waiting for database..."
          sleep 10
        done

    - name: Set up database
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
      run: |
        echo "Setting up the database"
        bundle exec rails db:create
        bundle exec rails db:migrate
        echo "Database setup complete"

    - name: Run tests
      run: bundle exec rspec
